### ISSUE TITLE
Error on start (Spigot 1.13)

### ISSUE THREAD

**Issue by AngryKiller** [Norech/CraftingPolicy#1]
`[20:14:21 INFO]: [CraftingPolicy] Enabling CraftingPolicy v1.0.1
[20:14:21 ERROR]: Error occurred while enabling CraftingPolicy v1.0.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.norech.craftingpolicy.EventListener.<init>(EventListener.java:23) ~[?:?]
	at com.norech.craftingpolicy.Main.onEnable(Main.java:27) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.reload(CraftServer.java:798) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.Bukkit.reload(Bukkit.java:527) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchServerCommand(CraftServer.java:678) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at net.minecraft.server.v1_13_R1.DedicatedServer.aW(DedicatedServer.java:453) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:412) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

**Comment by norech** [comment]
Fixed.
